class_name SimEvents
extends RefCounted

const UNIT_SPAWNED: String = "unit_spawned"
const UNIT_TARGET_CHANGED: String = "unit_target_changed"
const UNIT_BLOCKED: String = "unit_blocked"
const STRUCTURE_DAMAGED: String = "structure_damaged"
const STRUCTURE_DESTROYED: String = "structure_destroyed"
const PATHOGEN_DAMAGED: String = "pathogen_damaged"
const PATHOGEN_KILLED: String = "pathogen_killed"
const TOWER_FIRED: String = "tower_fired"
const SPLASH: String = "splash"
const PROJECTILE_SPAWNED: String = "projectile_spawned"
const PROJECTILE_HIT: String = "projectile_hit"
const PROJECTILE_FIZZLED: String = "projectile_fizzled"
const ANALYSIS_COMPLETE: String = "analysis_complete"
const BIOFILM_CHANGED: String = "biofilm_changed"
const HIJACK_STARTED: String = "hijack_started"
const HIJACK_COMPLETE: String = "hijack_complete"
const HIJACK_INTERRUPTED: String = "hijack_interrupted"
const BATTLE_ENDED: String = "battle_ended"
