// Bundles data/*.json into src/generated/data.ts with the same content hash GameConfig.content_hash uses:
// sha256 of rules + structures + pathogens file text (UTF-8, no flag overrides).
// The server uses this only to reject mismatched clients, never to run rules.
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const read = (name) => readFileSync(join(root, "data", name), "utf8");
const rules = read("game_rules.json");
const structures = read("structures.json");
const pathogens = read("pathogens.json");
const hash = createHash("sha256").update(rules + structures + pathogens, "utf8").digest("hex");

const out = join(root, "server", "src", "generated");
mkdirSync(out, { recursive: true });
const body =
  "// GENERATED by scripts/gen_data.mjs from data/*.json. Do not edit.\n" +
  `export const CONTENT_HASH: string = ${JSON.stringify(hash)};\n` +
  `export const DATA: { game_rules: any; structures: any; pathogens: any } = {\n` +
  `  game_rules: ${rules.trim()},\n  structures: ${structures.trim()},\n  pathogens: ${pathogens.trim()},\n};\n`;
writeFileSync(join(out, "data.ts"), body);
